const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
  matchScore: z
    .number()
    .describe(
      " score between 0 and 100 indicating how well the candidate's profile matches the job describe",
    ),
  technicalQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The technical question can be asked in the interview"),
        intension: z
          .string()
          .describe("The intension of interviewer behind asking this question"),
        answer: z
          .string()
          .describe(
            "How to answer this question , what point to cover, what approach to take etc.",
          ),
      }),
    )
    .describe(
      "Technical question that can be asked in the interview along with their intension and how to answer them",
    ),

  behaviouralQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The behavioural question can be asked in the interview"),
        intension: z
          .string()
          .describe("The intension of interviewer behind asking this question"),
        answer: z
          .string()
          .describe(
            "How to answer this question , what point to cover, what approach to take etc.",
          ),
      }),
    )
    .describe(
      "Behavioural question that can be asked in the interview along with their intension and how to answer them",
    ),

  skillGap: z
    .array(
      z.object({
        skill: z.string().describe("The skill in which candidate is lacking"),
        severity: z
          .enum(["low", "medium", "high"])
          .describe("The severity of this skill gap"),
      }),
    )
    .describe(
      "List of skills in which candidate is lacking along with their severity",
    ),

  preparationPlan: z
    .array(
      z.object({
        day: z.number().describe("The day number of preparation plan"),
        focus: z
          .string()
          .describe("The main focus of that day in preparation plan"),
        tasks: z
          .array(z.string())
          .describe(
            "The list of tasks to be done on that day in preparation plan",
          ),
      }),
    )
    .describe(
      "A day-wise preparation plan for the candidate to prepare for the interview effectively",
    ),
  title: z
    .string()
    .describe(
      "The title of the job for which the interview report is generated",
    ),
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `Generate an interview report for a candidate with the following details:
  Resume: ${resume}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}
  `
;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-lite",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
responseJsonSchema: z.toJSONSchema(interviewReportSchema)
    },
  });
   
  return JSON.parse(response.text);
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent,{waitUntil: "networkidle0"});


  const pdfBuffer = await page.pdf({ format: "A4",margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        } });
  await browser.close();
  return pdfBuffer;
}

async function generateResumePdf({resume,selfDescription,jobDescription}){ 

  const resumepdfSchema = z.object({
    html: z.string().describe("The html content of the resume which can be converted to pdf using any library like puppeteer")
  })


  const prompt = `Generate a resume for a candidate with the following details:
              resume: ${resume}
              selfDescription: ${selfDescription}
              jobDescription: ${jobDescription}
              the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
              The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
              The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
              you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
              The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
              The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
  `

const response = await ai.models.generateContent({
  model: "gemini-2.5-flash-lite",
  contents: prompt,
  config: {
    responseMimeType: "application/json",
    responseJsonSchema: z.toJSONSchema(resumepdfSchema)
  },

})
const jsonContent =  JSON.parse(response.text)
const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
return pdfBuffer
}
module.exports = {generateInterviewReport, generateResumePdf};
